---
title: "Links"
---

<br>

-   [CPUSA.org](https://cpusa.org) — The Party's official website. Official statements on current events and much more.

-   [People's World](https://www.peoplesworld.org/) — Continuing the Daily Worker, providing working class news and analysis since 1924.

-   [International Publishers](https://intpubnyc.com) — Publishers specializing in Marxist works of economics, political theory, and history.

-   [The Marxist Classes](https://www.cpusa.org/article_category/marxist-classes/) — The CPUSA's core educational series, produced by the Education Commission.

-   [Bringing Out the Red: What Being An EMS Worker Taught Me](https://cpusa.org/article/bringing-out-the-red-what-being-an-ems-worker-taught-me/) — An article from one of our members about his experiences in emergency medicine and how they contributed to his political development.

<br>

<br>

------------------------------------------------------------------------

#### Ready to get involved? {style="text-align: center"}

<br>

If you think you're ready to take the next step and join the Party, you have two options:

You can join via [the Party's official form](https://cpusa.org/join) at CPUSA.org, **or** use [our direct form](https://docs.google.com/forms/d/e/1FAIpQLSe-fWp2dtyBaVpYY21GCcX465iHk3lB6j_T7YzboTZQmdbPIw/viewform).
